// <auto-generated />
namespace THWeb_BigSchool.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class kdinh_1911061106 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(kdinh_1911061106));
        
        string IMigrationMetadata.Id
        {
            get { return "202303160646220_kdinh_1911061106"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
